world: hub
x: 156
y: 96
z: 282
yaw: 92
pitch: 3
serverName: Hub
packEnabled: true
titleEnabled: true
flightForDonorsEnabled: false
canSelectLobbies: false

hubs:
  Hub1:
    name: Hub1
    server: Hub1